version: "3"
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.develop
    ports:
      - '3000:3000'
    environment:
      CRAWLER_DOMAIN: http://crawler:3000
      SERVER_PORT: 3000
      DATABASE_URL: postgresql://postgres:123456@database:5432/voary-local
      EMAIL_SECRET_KEY: teste123
      APP_DOMAIN: https://dev.voary.io
      JWT_SECRET: 'voary_fly'
    volumes:
      - ./src:/app/src
    depends_on:
      - database
  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: voary-local
    ports:
      - "5432:5432"
    volumes:
      - /database:/var/lib/postgresql/data
